version: '3.4'

services:
    djangoguninginx:
        build:
            context: .
            dockerfile: Dockerfile.prd
        command: gunicorn djangoguninginx.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/opt/djangoguninginx/staticfiles
        expose:         # Accessible to other containers (specifically to nginx only)
            - 8000
        env_file: 
            - ./djangoguninginx.prd.env
        depends_on: 
            - postgresql
    postgresql:
        image: postgres:11.8-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./db.prd.env
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/opt/djangoguninginx/staticfiles
        ports:
            - 1337:80    # HOST:CONTAINER (Port 80 of container is accessible on 1337 of host)
        depends_on:
            - djangoguninginx

volumes:
    postgres_data:
    static_volume: